version: "3"
services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Wcs.37000
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/brocenscene:v1.0
    ports:
      - "8055:80"

volumes:
  db_data: {}